[2024-05-03T18:19:42.254+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T18:19:42.268+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_backup_catchfill.task1 scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-05-03T18:19:42.272+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_backup_catchfill.task1 scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-05-03T18:19:42.272+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-03T18:19:42.278+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task1> on 2024-05-01 00:00:00+00:00
[2024-05-03T18:19:42.282+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1771) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T18:19:42.282+0000] {standard_task_runner.py:63} INFO - Started process 1773 to run task
[2024-05-03T18:19:42.282+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_backup_catchfill', 'task1', 'scheduled__2024-05-01T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/dag_backup_catchfill.py', '--cfg-path', '/tmp/tmplx2kpr7j']
[2024-05-03T18:19:42.283+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask task1
[2024-05-03T18:19:42.303+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_backup_catchfill.task1 scheduled__2024-05-01T00:00:00+00:00 [running]> on host 697ad57716e5
[2024-05-03T18:19:42.341+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_backup_catchfill' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-01T00:00:00+00:00'
[2024-05-03T18:19:42.342+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T18:19:42.348+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-03T18:19:42.349+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo This is a simple bash command.']
[2024-05-03T18:19:42.353+0000] {subprocess.py:86} INFO - Output:
[2024-05-03T18:19:42.354+0000] {subprocess.py:93} INFO - This is a simple bash command.
[2024-05-03T18:19:42.354+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-03T18:19:42.355+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T18:19:42.366+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_backup_catchfill, task_id=task1, execution_date=20240501T000000, start_date=20240503T181942, end_date=20240503T181942
[2024-05-03T18:19:42.382+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-03T18:19:42.390+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T18:19:42.391+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
