[2024-05-05T03:28:55.248+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T03:28:55.261+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_space.estimate_table_size scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-05-05T03:28:55.264+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_space.estimate_table_size scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-05-05T03:28:55.265+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 6
[2024-05-05T03:28:55.270+0000] {taskinstance.py:2327} INFO - Executing <Task(MySqlOperator): estimate_table_size> on 2024-05-04 00:00:00+00:00
[2024-05-05T03:28:55.273+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_space', 'estimate_table_size', 'scheduled__2024-05-04T00:00:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmp6qqcbgq1']
[2024-05-05T03:28:55.274+0000] {standard_task_runner.py:91} INFO - Job 123: Subtask estimate_table_size
[2024-05-05T03:28:55.276+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=470) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T03:28:55.276+0000] {standard_task_runner.py:63} INFO - Started process 471 to run task
[2024-05-05T03:28:55.296+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_space.estimate_table_size scheduled__2024-05-04T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-05T03:28:55.331+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_space' AIRFLOW_CTX_TASK_ID='estimate_table_size' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-04T00:00:00+00:00'
[2024-05-05T03:28:55.331+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T03:28:55.337+0000] {sql.py:276} INFO - Executing: 
            SELECT round(sum(data_length + index_length) / 1024 / 1024, 2)
            FROM information_schema.TABLES
            WHERE table_schema = 'client_rw' AND table_name = 'fc_account_master';
        
[2024-05-05T03:28:55.341+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2024-05-05T03:28:55.345+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2024-05-05T03:28:55.351+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T03:28:55.352+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 195, in get_conn
    return MySQLdb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'host.docker.internal' (115)")
[2024-05-05T03:28:55.356+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_space, task_id=estimate_table_size, execution_date=20240504T000000, start_date=20240505T032855, end_date=20240505T032855
[2024-05-05T03:28:55.363+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 123 for task estimate_table_size ((2002, "Can't connect to server on 'host.docker.internal' (115)"); 471)
[2024-05-05T03:28:55.379+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T03:28:55.384+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class MySqlOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-05-05T03:28:55.389+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T03:28:55.390+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
