[2024-05-04T10:40:40.324+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T10:40:40.356+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T10:40:40.361+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T10:40:40.362+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-04T10:40:40.373+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task2> on 2024-05-03 00:00:00+00:00
[2024-05-04T10:40:40.380+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=618) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T10:40:40.380+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_mysql', 'task2', 'scheduled__2024-05-03T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpsnt9vf_n']
[2024-05-04T10:40:40.385+0000] {standard_task_runner.py:63} INFO - Started process 624 to run task
[2024-05-04T10:40:40.385+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask task2
[2024-05-04T10:40:40.426+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_mysql.task2 scheduled__2024-05-03T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-04T10:40:40.473+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_mysql' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T00:00:00+00:00'
[2024-05-04T10:40:40.473+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T10:40:40.482+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-04T10:40:40.482+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mysqldump ']
[2024-05-04T10:40:40.487+0000] {subprocess.py:86} INFO - Output:
[2024-05-04T10:40:40.490+0000] {subprocess.py:93} INFO - Usage: mysqldump [OPTIONS] database [tables]
[2024-05-04T10:40:40.490+0000] {subprocess.py:93} INFO - OR     mysqldump [OPTIONS] --databases DB1 [DB2 DB3...]
[2024-05-04T10:40:40.490+0000] {subprocess.py:93} INFO - OR     mysqldump [OPTIONS] --all-databases
[2024-05-04T10:40:40.491+0000] {subprocess.py:93} INFO - OR     mysqldump [OPTIONS] --system=[SYSTEMOPTIONS]]
[2024-05-04T10:40:40.491+0000] {subprocess.py:93} INFO - For more options, use mysqldump --help
[2024-05-04T10:40:40.491+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-04T10:40:40.491+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T10:40:40.497+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-04T10:40:40.500+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_mysql, task_id=task2, execution_date=20240503T000000, start_date=20240504T104040, end_date=20240504T104040
[2024-05-04T10:40:40.506+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 41 for task task2 (Bash command failed. The command returned a non-zero exit code 1.; 624)
[2024-05-04T10:40:40.527+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T10:40:40.536+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T10:40:40.537+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-04T10:42:21.579+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T10:42:21.597+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T10:42:21.603+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T10:42:21.604+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-04T10:42:21.612+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task2> on 2024-05-03 00:00:00+00:00
[2024-05-04T10:42:21.618+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=731) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T10:42:21.618+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_mysql', 'task2', 'scheduled__2024-05-03T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmp0e6qz9qo']
[2024-05-04T10:42:21.619+0000] {standard_task_runner.py:63} INFO - Started process 737 to run task
[2024-05-04T10:42:21.619+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask task2
[2024-05-04T10:42:21.650+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_mysql.task2 scheduled__2024-05-03T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-04T10:42:21.700+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_mysql' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T00:00:00+00:00'
[2024-05-04T10:42:21.702+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T10:42:21.712+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-04T10:42:21.714+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mysqldump']
[2024-05-04T10:42:21.719+0000] {subprocess.py:86} INFO - Output:
[2024-05-04T10:42:21.722+0000] {subprocess.py:93} INFO - Usage: mysqldump [OPTIONS] database [tables]
[2024-05-04T10:42:21.725+0000] {subprocess.py:93} INFO - OR     mysqldump [OPTIONS] --databases DB1 [DB2 DB3...]
[2024-05-04T10:42:21.726+0000] {subprocess.py:93} INFO - OR     mysqldump [OPTIONS] --all-databases
[2024-05-04T10:42:21.728+0000] {subprocess.py:93} INFO - OR     mysqldump [OPTIONS] --system=[SYSTEMOPTIONS]]
[2024-05-04T10:42:21.730+0000] {subprocess.py:93} INFO - For more options, use mysqldump --help
[2024-05-04T10:42:21.731+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-04T10:42:21.733+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T10:42:21.744+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-04T10:42:21.750+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_mysql, task_id=task2, execution_date=20240503T000000, start_date=20240504T104221, end_date=20240504T104221
[2024-05-04T10:42:21.765+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 47 for task task2 (Bash command failed. The command returned a non-zero exit code 1.; 737)
[2024-05-04T10:42:21.801+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T10:42:21.811+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T10:42:21.812+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-04T10:43:58.931+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T10:43:58.946+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T10:43:58.950+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T10:43:58.950+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-04T10:43:58.957+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task2> on 2024-05-03 00:00:00+00:00
[2024-05-04T10:43:58.962+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_mysql', 'task2', 'scheduled__2024-05-03T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpxhbphuyu']
[2024-05-04T10:43:58.963+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=862) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T10:43:58.964+0000] {standard_task_runner.py:91} INFO - Job 51: Subtask task2
[2024-05-04T10:43:58.964+0000] {standard_task_runner.py:63} INFO - Started process 865 to run task
[2024-05-04T10:43:58.986+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_mysql.task2 scheduled__2024-05-03T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-04T10:43:59.023+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_mysql' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T00:00:00+00:00'
[2024-05-04T10:43:59.024+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T10:43:59.032+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-04T10:43:59.033+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mysqldump -u root -p12345678 client_rw fc_account_master > first.sql']
[2024-05-04T10:43:59.037+0000] {subprocess.py:86} INFO - Output:
[2024-05-04T10:43:59.042+0000] {subprocess.py:93} INFO - mysqldump: Got error: 2002: "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)" when trying to connect
[2024-05-04T10:43:59.042+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-05-04T10:43:59.043+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T10:43:59.048+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-04T10:43:59.050+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_mysql, task_id=task2, execution_date=20240503T000000, start_date=20240504T104358, end_date=20240504T104359
[2024-05-04T10:43:59.056+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 51 for task task2 (Bash command failed. The command returned a non-zero exit code 2.; 865)
[2024-05-04T10:43:59.064+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T10:43:59.072+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T10:43:59.073+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-04T10:45:32.357+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T10:45:32.372+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T10:45:32.376+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T10:45:32.376+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-04T10:45:32.383+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task2> on 2024-05-03 00:00:00+00:00
[2024-05-04T10:45:32.386+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_mysql', 'task2', 'scheduled__2024-05-03T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmp_l3phdv9']
[2024-05-04T10:45:32.387+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=967) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T10:45:32.388+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask task2
[2024-05-04T10:45:32.388+0000] {standard_task_runner.py:63} INFO - Started process 970 to run task
[2024-05-04T10:45:32.409+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_mysql.task2 scheduled__2024-05-03T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-04T10:45:32.446+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_mysql' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T00:00:00+00:00'
[2024-05-04T10:45:32.446+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T10:45:32.454+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-04T10:45:32.454+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mysqldump -u root -p12345678 client_rw fc_account_master > first.sql']
[2024-05-04T10:45:32.458+0000] {subprocess.py:86} INFO - Output:
[2024-05-04T10:45:32.462+0000] {subprocess.py:93} INFO - mysqldump: Got error: 2002: "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)" when trying to connect
[2024-05-04T10:45:32.462+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-05-04T10:45:32.463+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T10:45:32.468+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-04T10:45:32.471+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_mysql, task_id=task2, execution_date=20240503T000000, start_date=20240504T104532, end_date=20240504T104532
[2024-05-04T10:45:32.477+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 54 for task task2 (Bash command failed. The command returned a non-zero exit code 2.; 970)
[2024-05-04T10:45:32.486+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T10:45:32.494+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T10:45:32.495+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
