[2024-05-04T15:27:53.317+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T15:27:53.333+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_space.check_space scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T15:27:53.338+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_space.check_space scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T15:27:53.339+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-04T15:27:53.345+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): check_space> on 2024-05-03 00:00:00+00:00
[2024-05-04T15:27:53.352+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_space', 'check_space', 'scheduled__2024-05-03T00:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpnyzl1hoi']
[2024-05-04T15:27:53.354+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=260) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T15:27:53.357+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask check_space
[2024-05-04T15:27:53.357+0000] {standard_task_runner.py:63} INFO - Started process 264 to run task
[2024-05-04T15:27:53.388+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_space.check_space scheduled__2024-05-03T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-04T15:27:53.428+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_space' AIRFLOW_CTX_TASK_ID='check_space' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T00:00:00+00:00'
[2024-05-04T15:27:53.431+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T15:27:53.438+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-04T15:27:53.438+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', ' df -H opt/***/dags']
[2024-05-04T15:27:53.442+0000] {subprocess.py:86} INFO - Output:
[2024-05-04T15:27:53.444+0000] {subprocess.py:93} INFO - df: opt/***/dags: No such file or directory
[2024-05-04T15:27:53.444+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-04T15:27:53.444+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T15:27:53.449+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-04T15:27:53.451+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_space, task_id=check_space, execution_date=20240503T000000, start_date=20240504T152753, end_date=20240504T152753
[2024-05-04T15:27:53.457+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 67 for task check_space (Bash command failed. The command returned a non-zero exit code 1.; 264)
[2024-05-04T15:27:53.497+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T15:27:53.505+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T15:27:53.506+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-04T15:29:38.351+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T15:29:38.366+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_space.check_space scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T15:29:38.372+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_space.check_space scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T15:29:38.373+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-04T15:29:38.379+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): check_space> on 2024-05-03 00:00:00+00:00
[2024-05-04T15:29:38.384+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_space', 'check_space', 'scheduled__2024-05-03T00:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmp3u5jb6e4']
[2024-05-04T15:29:38.386+0000] {standard_task_runner.py:91} INFO - Job 71: Subtask check_space
[2024-05-04T15:29:38.386+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=396) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T15:29:38.387+0000] {standard_task_runner.py:63} INFO - Started process 400 to run task
[2024-05-04T15:29:38.416+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_space.check_space scheduled__2024-05-03T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-04T15:29:38.452+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_space' AIRFLOW_CTX_TASK_ID='check_space' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T00:00:00+00:00'
[2024-05-04T15:29:38.453+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T15:29:38.461+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-04T15:29:38.461+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', ' df -H opt']
[2024-05-04T15:29:38.465+0000] {subprocess.py:86} INFO - Output:
[2024-05-04T15:29:38.468+0000] {subprocess.py:93} INFO - df: opt: No such file or directory
[2024-05-04T15:29:38.468+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-04T15:29:38.468+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T15:29:38.474+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-04T15:29:38.476+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_space, task_id=check_space, execution_date=20240503T000000, start_date=20240504T152938, end_date=20240504T152938
[2024-05-04T15:29:38.482+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 71 for task check_space (Bash command failed. The command returned a non-zero exit code 1.; 400)
[2024-05-04T15:29:38.487+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T15:29:38.494+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T15:29:38.495+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
