[2024-05-04T15:31:49.151+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T15:31:49.164+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_space.check_space manual__2024-05-04T15:31:48.471580+00:00 [queued]>
[2024-05-04T15:31:49.168+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_space.check_space manual__2024-05-04T15:31:48.471580+00:00 [queued]>
[2024-05-04T15:31:49.168+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-04T15:31:49.173+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): check_space> on 2024-05-04 15:31:48.471580+00:00
[2024-05-04T15:31:49.176+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_space', 'check_space', 'manual__2024-05-04T15:31:48.471580+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpak9sgre5']
[2024-05-04T15:31:49.177+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=538) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T15:31:49.177+0000] {standard_task_runner.py:91} INFO - Job 75: Subtask check_space
[2024-05-04T15:31:49.177+0000] {standard_task_runner.py:63} INFO - Started process 539 to run task
[2024-05-04T15:31:49.196+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_space.check_space manual__2024-05-04T15:31:48.471580+00:00 [running]> on host f85b7a0b58b5
[2024-05-04T15:31:49.230+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_space' AIRFLOW_CTX_TASK_ID='check_space' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T15:31:48.471580+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-04T15:31:48.471580+00:00'
[2024-05-04T15:31:49.231+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T15:31:49.237+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-04T15:31:49.238+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', ' df -H opt/***/dags']
[2024-05-04T15:31:49.241+0000] {subprocess.py:86} INFO - Output:
[2024-05-04T15:31:49.242+0000] {subprocess.py:93} INFO - df: 'opt/***/dags': No such file or directory
[2024-05-04T15:31:49.242+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-04T15:31:49.243+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T15:31:49.247+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-04T15:31:49.249+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_space, task_id=check_space, execution_date=20240504T153148, start_date=20240504T153149, end_date=20240504T153149
[2024-05-04T15:31:49.254+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 75 for task check_space (Bash command failed. The command returned a non-zero exit code 1.; 539)
[2024-05-04T15:31:49.276+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T15:31:49.284+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T15:31:49.285+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
