[2024-05-19T03:18:45.088+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T03:18:45.138+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-19T03:18:45.171+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-19T03:18:45.173+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-19T03:18:45.209+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): analysis> on 2024-05-02 00:00:00+00:00
[2024-05-19T03:18:45.241+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_analysis', 'analysis', 'scheduled__2024-05-02T00:00:00+00:00', '--job-id', '561', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmp2chbxbe4']
[2024-05-19T03:18:45.246+0000] {standard_task_runner.py:91} INFO - Job 561: Subtask analysis
[2024-05-19T03:18:45.260+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=178) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-19T03:18:45.265+0000] {standard_task_runner.py:63} INFO - Started process 201 to run task
[2024-05-19T03:18:45.427+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_analysis.analysis scheduled__2024-05-02T00:00:00+00:00 [running]> on host cf8d95dc7aa1
[2024-05-19T03:18:45.602+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_analysis' AIRFLOW_CTX_TASK_ID='analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-02T00:00:00+00:00'
[2024-05-19T03:18:45.617+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T03:18:45.664+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T03:18:45.671+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'Bisheshs-MacBook-Pro.local:3306' (22)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag1.py", line 8, in run
    conn = connection.connect(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'Bisheshs-MacBook-Pro.local:3306' (22)
[2024-05-19T03:18:45.697+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_analysis, task_id=analysis, execution_date=20240502T000000, start_date=20240519T031845, end_date=20240519T031845
[2024-05-19T03:18:45.714+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 561 for task analysis (2003 (HY000): Can't connect to MySQL server on 'Bisheshs-MacBook-Pro.local:3306' (22); 201)
[2024-05-19T03:18:45.752+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T03:18:45.786+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T03:18:45.793+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-19T03:19:43.423+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T03:19:43.459+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-19T03:19:43.480+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-19T03:19:43.482+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-19T03:19:43.563+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): analysis> on 2024-05-02 00:00:00+00:00
[2024-05-19T03:19:43.596+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=259) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-19T03:19:43.606+0000] {standard_task_runner.py:63} INFO - Started process 280 to run task
[2024-05-19T03:19:43.599+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_analysis', 'analysis', 'scheduled__2024-05-02T00:00:00+00:00', '--job-id', '576', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpxrjgqa1q']
[2024-05-19T03:19:43.611+0000] {standard_task_runner.py:91} INFO - Job 576: Subtask analysis
[2024-05-19T03:19:43.739+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_analysis.analysis scheduled__2024-05-02T00:00:00+00:00 [running]> on host cf8d95dc7aa1
[2024-05-19T03:19:43.975+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_analysis' AIRFLOW_CTX_TASK_ID='analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-02T00:00:00+00:00'
[2024-05-19T03:19:43.976+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T03:19:44.221+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:15 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:44.509+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:17 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:44.521+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:19 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:44.537+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:21 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:44.566+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:23 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:44.750+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-19T03:19:44.753+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T03:19:44.769+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_analysis, task_id=analysis, execution_date=20240502T000000, start_date=20240519T031943, end_date=20240519T031944
[2024-05-19T03:19:44.803+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T03:19:44.852+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T03:19:44.861+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-19T03:20:56.089+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T03:20:56.125+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-19T03:20:56.144+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-19T03:20:56.145+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-19T03:20:56.185+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): analysis> on 2024-05-02 00:00:00+00:00
[2024-05-19T03:20:56.211+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=362) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-19T03:20:56.214+0000] {standard_task_runner.py:63} INFO - Started process 381 to run task
[2024-05-19T03:20:56.203+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_analysis', 'analysis', 'scheduled__2024-05-02T00:00:00+00:00', '--job-id', '594', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmp_o1_sft5']
[2024-05-19T03:20:56.221+0000] {standard_task_runner.py:91} INFO - Job 594: Subtask analysis
[2024-05-19T03:20:56.310+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_analysis.analysis scheduled__2024-05-02T00:00:00+00:00 [running]> on host cf8d95dc7aa1
[2024-05-19T03:20:56.468+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_analysis' AIRFLOW_CTX_TASK_ID='analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-02T00:00:00+00:00'
[2024-05-19T03:20:56.475+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T03:20:56.723+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:15 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:20:56.955+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:17 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:20:56.968+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:19 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:20:56.982+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:21 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:20:56.996+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:23 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:20:57.204+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-19T03:20:57.211+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T03:20:57.236+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_analysis, task_id=analysis, execution_date=20240502T000000, start_date=20240519T032056, end_date=20240519T032057
[2024-05-19T03:20:57.327+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T03:20:57.360+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T03:20:57.370+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
