[2024-05-16T11:19:49.259+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:19:49.306+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-16T11:19:49.321+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-16T11:19:49.331+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:19:49.406+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_table2> on 2024-05-09 00:00:00+00:00
[2024-05-16T11:19:49.418+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_table2', 'scheduled__2024-05-09T00:00:00+00:00', '--job-id', '401', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmp9xffbclv']
[2024-05-16T11:19:49.421+0000] {standard_task_runner.py:91} INFO - Job 401: Subtask import_table2
[2024-05-16T11:19:49.425+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=249) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:19:49.428+0000] {standard_task_runner.py:63} INFO - Started process 273 to run task
[2024-05-16T11:19:49.484+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_table2 scheduled__2024-05-09T00:00:00+00:00 [running]> on host 7084a6d88d3b
[2024-05-16T11:19:49.550+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_table2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T00:00:00+00:00'
[2024-05-16T11:19:49.552+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:19:49.560+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:19:49.562+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category.sql;\n                ']
[2024-05-16T11:19:49.577+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:19:49.673+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-16T11:19:49.675+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:19:49.694+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_tables, task_id=import_table2, execution_date=20240509T000000, start_date=20240516T111949, end_date=20240516T111949
[2024-05-16T11:19:49.744+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-16T11:19:49.801+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:19:49.847+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-16T11:22:31.746+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:22:31.769+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-16T11:22:31.779+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-16T11:22:31.780+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:22:31.798+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_table2> on 2024-05-09 00:00:00+00:00
[2024-05-16T11:22:31.811+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=528) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:22:31.815+0000] {standard_task_runner.py:63} INFO - Started process 544 to run task
[2024-05-16T11:22:31.812+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_table2', 'scheduled__2024-05-09T00:00:00+00:00', '--job-id', '453', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpa0tkm74g']
[2024-05-16T11:22:31.819+0000] {standard_task_runner.py:91} INFO - Job 453: Subtask import_table2
[2024-05-16T11:22:31.878+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_table2 scheduled__2024-05-09T00:00:00+00:00 [running]> on host 7084a6d88d3b
[2024-05-16T11:22:31.979+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_table2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T00:00:00+00:00'
[2024-05-16T11:22:31.980+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:22:31.997+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:22:32.004+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category.sql\n                ']
[2024-05-16T11:22:32.018+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:22:32.135+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-16T11:22:32.136+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:22:32.167+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_tables, task_id=import_table2, execution_date=20240509T000000, start_date=20240516T112231, end_date=20240516T112232
[2024-05-16T11:22:32.222+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-16T11:22:32.244+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:22:32.253+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-16T11:24:46.776+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:24:46.797+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-16T11:24:46.804+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-16T11:24:46.806+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:24:46.819+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_table2> on 2024-05-09 00:00:00+00:00
[2024-05-16T11:24:46.828+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=742) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:24:46.826+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_table2', 'scheduled__2024-05-09T00:00:00+00:00', '--job-id', '494', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmp40lo17oi']
[2024-05-16T11:24:46.832+0000] {standard_task_runner.py:91} INFO - Job 494: Subtask import_table2
[2024-05-16T11:24:46.831+0000] {standard_task_runner.py:63} INFO - Started process 757 to run task
[2024-05-16T11:24:46.878+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_table2 scheduled__2024-05-09T00:00:00+00:00 [running]> on host 7084a6d88d3b
[2024-05-16T11:24:46.940+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_table2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T00:00:00+00:00'
[2024-05-16T11:24:46.941+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:24:46.946+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:24:46.948+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category.sql\n                ']
[2024-05-16T11:24:46.953+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:24:47.000+0000] {subprocess.py:93} INFO - ERROR 1146 (42S02) at line 41: Table 'test.product_category' doesn't exist
[2024-05-16T11:24:47.002+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-16T11:24:47.003+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:24:47.011+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-16T11:24:47.014+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_tables, task_id=import_table2, execution_date=20240509T000000, start_date=20240516T112446, end_date=20240516T112447
[2024-05-16T11:24:47.021+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 494 for task import_table2 (Bash command failed. The command returned a non-zero exit code 1.; 757)
[2024-05-16T11:24:47.057+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-16T11:24:47.066+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:24:47.066+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
