[2024-05-04T10:40:40.250+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T10:40:40.274+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-04T10:40:40.281+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-04T10:40:40.282+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-04T10:40:40.298+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task2> on 2024-05-02 00:00:00+00:00
[2024-05-04T10:40:40.305+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_mysql', 'task2', 'scheduled__2024-05-02T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpj7u64t0h']
[2024-05-04T10:40:40.312+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask task2
[2024-05-04T10:40:40.307+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=615) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T10:40:40.313+0000] {standard_task_runner.py:63} INFO - Started process 621 to run task
[2024-05-04T10:40:40.356+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_mysql.task2 scheduled__2024-05-02T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-04T10:40:40.419+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_mysql' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-02T00:00:00+00:00'
[2024-05-04T10:40:40.421+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T10:40:40.431+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-04T10:40:40.432+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mysqldump ']
[2024-05-04T10:40:40.438+0000] {subprocess.py:86} INFO - Output:
[2024-05-04T10:40:40.442+0000] {subprocess.py:93} INFO - Usage: mysqldump [OPTIONS] database [tables]
[2024-05-04T10:40:40.443+0000] {subprocess.py:93} INFO - OR     mysqldump [OPTIONS] --databases DB1 [DB2 DB3...]
[2024-05-04T10:40:40.444+0000] {subprocess.py:93} INFO - OR     mysqldump [OPTIONS] --all-databases
[2024-05-04T10:40:40.445+0000] {subprocess.py:93} INFO - OR     mysqldump [OPTIONS] --system=[SYSTEMOPTIONS]]
[2024-05-04T10:40:40.445+0000] {subprocess.py:93} INFO - For more options, use mysqldump --help
[2024-05-04T10:40:40.447+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-04T10:40:40.448+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T10:40:40.455+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-04T10:40:40.459+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_mysql, task_id=task2, execution_date=20240502T000000, start_date=20240504T104040, end_date=20240504T104040
[2024-05-04T10:40:40.467+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 38 for task task2 (Bash command failed. The command returned a non-zero exit code 1.; 621)
[2024-05-04T10:40:40.495+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T10:40:40.503+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T10:40:40.504+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-04T10:42:21.533+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T10:42:21.554+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-04T10:42:21.558+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-04T10:42:21.559+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-04T10:42:21.569+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task2> on 2024-05-02 00:00:00+00:00
[2024-05-04T10:42:21.576+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=729) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T10:42:21.577+0000] {standard_task_runner.py:63} INFO - Started process 734 to run task
[2024-05-04T10:42:21.574+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_mysql', 'task2', 'scheduled__2024-05-02T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmp0ky8ecl2']
[2024-05-04T10:42:21.583+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask task2
[2024-05-04T10:42:21.613+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_mysql.task2 scheduled__2024-05-02T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-04T10:42:21.661+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_mysql' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-02T00:00:00+00:00'
[2024-05-04T10:42:21.663+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T10:42:21.686+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-04T10:42:21.690+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mysqldump']
[2024-05-04T10:42:21.699+0000] {subprocess.py:86} INFO - Output:
[2024-05-04T10:42:21.704+0000] {subprocess.py:93} INFO - Usage: mysqldump [OPTIONS] database [tables]
[2024-05-04T10:42:21.706+0000] {subprocess.py:93} INFO - OR     mysqldump [OPTIONS] --databases DB1 [DB2 DB3...]
[2024-05-04T10:42:21.706+0000] {subprocess.py:93} INFO - OR     mysqldump [OPTIONS] --all-databases
[2024-05-04T10:42:21.709+0000] {subprocess.py:93} INFO - OR     mysqldump [OPTIONS] --system=[SYSTEMOPTIONS]]
[2024-05-04T10:42:21.711+0000] {subprocess.py:93} INFO - For more options, use mysqldump --help
[2024-05-04T10:42:21.712+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-04T10:42:21.714+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T10:42:21.728+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-04T10:42:21.734+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_mysql, task_id=task2, execution_date=20240502T000000, start_date=20240504T104221, end_date=20240504T104221
[2024-05-04T10:42:21.742+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 44 for task task2 (Bash command failed. The command returned a non-zero exit code 1.; 734)
[2024-05-04T10:42:21.762+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T10:42:21.778+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T10:42:21.780+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-04T10:43:58.891+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T10:43:58.907+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-04T10:43:58.911+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-04T10:43:58.911+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-04T10:43:58.918+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task2> on 2024-05-02 00:00:00+00:00
[2024-05-04T10:43:58.922+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_mysql', 'task2', 'scheduled__2024-05-02T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmp5uv4j7ns']
[2024-05-04T10:43:58.923+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=861) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T10:43:58.924+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask task2
[2024-05-04T10:43:58.924+0000] {standard_task_runner.py:63} INFO - Started process 864 to run task
[2024-05-04T10:43:58.947+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_mysql.task2 scheduled__2024-05-02T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-04T10:43:58.984+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_mysql' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-02T00:00:00+00:00'
[2024-05-04T10:43:58.984+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T10:43:58.993+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-04T10:43:58.993+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mysqldump -u root -p12345678 client_rw fc_account_master > first.sql']
[2024-05-04T10:43:58.997+0000] {subprocess.py:86} INFO - Output:
[2024-05-04T10:43:59.001+0000] {subprocess.py:93} INFO - mysqldump: Got error: 2002: "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)" when trying to connect
[2024-05-04T10:43:59.001+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-05-04T10:43:59.002+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T10:43:59.006+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-04T10:43:59.009+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_mysql, task_id=task2, execution_date=20240502T000000, start_date=20240504T104358, end_date=20240504T104359
[2024-05-04T10:43:59.015+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task task2 (Bash command failed. The command returned a non-zero exit code 2.; 864)
[2024-05-04T10:43:59.024+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T10:43:59.031+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T10:43:59.032+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-04T10:45:32.324+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T10:45:32.338+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-04T10:45:32.342+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_mysql.task2 scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-04T10:45:32.343+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-04T10:45:32.350+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task2> on 2024-05-02 00:00:00+00:00
[2024-05-04T10:45:32.354+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_mysql', 'task2', 'scheduled__2024-05-02T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpgpfefhl3']
[2024-05-04T10:45:32.355+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=966) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T10:45:32.355+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask task2
[2024-05-04T10:45:32.358+0000] {standard_task_runner.py:63} INFO - Started process 969 to run task
[2024-05-04T10:45:32.382+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_mysql.task2 scheduled__2024-05-02T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-04T10:45:32.417+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_mysql' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-02T00:00:00+00:00'
[2024-05-04T10:45:32.418+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T10:45:32.425+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-04T10:45:32.426+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mysqldump -u root -p12345678 client_rw fc_account_master > first.sql']
[2024-05-04T10:45:32.430+0000] {subprocess.py:86} INFO - Output:
[2024-05-04T10:45:32.435+0000] {subprocess.py:93} INFO - mysqldump: Got error: 2002: "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)" when trying to connect
[2024-05-04T10:45:32.435+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-05-04T10:45:32.436+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T10:45:32.441+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-04T10:45:32.443+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_mysql, task_id=task2, execution_date=20240502T000000, start_date=20240504T104532, end_date=20240504T104532
[2024-05-04T10:45:32.448+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 53 for task task2 (Bash command failed. The command returned a non-zero exit code 2.; 969)
[2024-05-04T10:45:32.458+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T10:45:32.466+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T10:45:32.467+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
