[2024-05-19T03:18:46.259+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T03:18:46.276+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-05-19T03:18:46.279+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-05-19T03:18:46.280+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-19T03:18:46.289+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): analysis> on 2024-05-14 00:00:00+00:00
[2024-05-19T03:18:46.298+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=210) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-19T03:18:46.297+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_analysis', 'analysis', 'scheduled__2024-05-14T00:00:00+00:00', '--job-id', '571', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmp220_wkvq']
[2024-05-19T03:18:46.299+0000] {standard_task_runner.py:63} INFO - Started process 221 to run task
[2024-05-19T03:18:46.299+0000] {standard_task_runner.py:91} INFO - Job 571: Subtask analysis
[2024-05-19T03:18:46.341+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_analysis.analysis scheduled__2024-05-14T00:00:00+00:00 [running]> on host cf8d95dc7aa1
[2024-05-19T03:18:46.381+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_analysis' AIRFLOW_CTX_TASK_ID='analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-14T00:00:00+00:00'
[2024-05-19T03:18:46.383+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T03:18:46.394+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T03:18:46.394+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'Bisheshs-MacBook-Pro.local:3306' (22)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag1.py", line 8, in run
    conn = connection.connect(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'Bisheshs-MacBook-Pro.local:3306' (22)
[2024-05-19T03:18:46.400+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_analysis, task_id=analysis, execution_date=20240514T000000, start_date=20240519T031846, end_date=20240519T031846
[2024-05-19T03:18:46.406+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 571 for task analysis (2003 (HY000): Can't connect to MySQL server on 'Bisheshs-MacBook-Pro.local:3306' (22); 221)
[2024-05-19T03:18:46.442+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T03:18:46.449+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T03:18:46.450+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-19T03:19:45.152+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T03:19:45.179+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-05-19T03:19:45.185+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-05-19T03:19:45.185+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-19T03:19:45.197+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): analysis> on 2024-05-14 00:00:00+00:00
[2024-05-19T03:19:45.205+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=290) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-19T03:19:45.208+0000] {standard_task_runner.py:63} INFO - Started process 304 to run task
[2024-05-19T03:19:45.205+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_analysis', 'analysis', 'scheduled__2024-05-14T00:00:00+00:00', '--job-id', '589', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpv808jd7j']
[2024-05-19T03:19:45.216+0000] {standard_task_runner.py:91} INFO - Job 589: Subtask analysis
[2024-05-19T03:19:45.255+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_analysis.analysis scheduled__2024-05-14T00:00:00+00:00 [running]> on host cf8d95dc7aa1
[2024-05-19T03:19:45.336+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_analysis' AIRFLOW_CTX_TASK_ID='analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-14T00:00:00+00:00'
[2024-05-19T03:19:45.337+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T03:19:45.406+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:15 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:45.456+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:17 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:45.459+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:19 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:45.469+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:21 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:45.475+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:23 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:45.533+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-19T03:19:45.534+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T03:19:45.539+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_analysis, task_id=analysis, execution_date=20240514T000000, start_date=20240519T031945, end_date=20240519T031945
[2024-05-19T03:19:45.558+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T03:19:45.567+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T03:19:45.568+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-19T03:20:57.562+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T03:20:57.588+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-05-19T03:20:57.599+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-05-19T03:20:57.600+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-19T03:20:57.618+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): analysis> on 2024-05-14 00:00:00+00:00
[2024-05-19T03:20:57.634+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=394) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-19T03:20:57.637+0000] {standard_task_runner.py:63} INFO - Started process 409 to run task
[2024-05-19T03:20:57.635+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_analysis', 'analysis', 'scheduled__2024-05-14T00:00:00+00:00', '--job-id', '607', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmprtwjqtip']
[2024-05-19T03:20:57.648+0000] {standard_task_runner.py:91} INFO - Job 607: Subtask analysis
[2024-05-19T03:20:57.724+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_analysis.analysis scheduled__2024-05-14T00:00:00+00:00 [running]> on host cf8d95dc7aa1
[2024-05-19T03:20:57.776+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_analysis' AIRFLOW_CTX_TASK_ID='analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-14T00:00:00+00:00'
[2024-05-19T03:20:57.777+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T03:20:57.834+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:15 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:20:57.879+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:17 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:20:57.882+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:19 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:20:57.885+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:21 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:20:57.887+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:23 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:20:57.944+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-19T03:20:57.944+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T03:20:57.949+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_analysis, task_id=analysis, execution_date=20240514T000000, start_date=20240519T032057, end_date=20240519T032057
[2024-05-19T03:20:57.987+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T03:20:57.996+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T03:20:57.997+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
