[2024-05-16T11:19:50.623+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:19:50.654+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_table3 scheduled__2024-05-12T00:00:00+00:00 [queued]>
[2024-05-16T11:19:50.664+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_table3 scheduled__2024-05-12T00:00:00+00:00 [queued]>
[2024-05-16T11:19:50.665+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:19:50.695+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_table3> on 2024-05-12 00:00:00+00:00
[2024-05-16T11:19:50.702+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_table3', 'scheduled__2024-05-12T00:00:00+00:00', '--job-id', '417', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpu_4zahm3']
[2024-05-16T11:19:50.710+0000] {standard_task_runner.py:91} INFO - Job 417: Subtask import_table3
[2024-05-16T11:19:50.708+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=326) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:19:50.713+0000] {standard_task_runner.py:63} INFO - Started process 339 to run task
[2024-05-16T11:19:50.763+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_table3 scheduled__2024-05-12T00:00:00+00:00 [running]> on host 7084a6d88d3b
[2024-05-16T11:19:50.856+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_table3' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-12T00:00:00+00:00'
[2024-05-16T11:19:50.858+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:19:50.867+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:19:50.870+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category_map.sql;\n                ']
[2024-05-16T11:19:50.879+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:19:50.980+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-16T11:19:50.983+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:19:51.039+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_tables, task_id=import_table3, execution_date=20240512T000000, start_date=20240516T111950, end_date=20240516T111951
[2024-05-16T11:19:51.100+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-16T11:19:51.123+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:19:51.124+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-16T11:22:33.226+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:22:33.264+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_table3 scheduled__2024-05-12T00:00:00+00:00 [queued]>
[2024-05-16T11:22:33.271+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_table3 scheduled__2024-05-12T00:00:00+00:00 [queued]>
[2024-05-16T11:22:33.272+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:22:33.283+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_table3> on 2024-05-12 00:00:00+00:00
[2024-05-16T11:22:33.290+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=577) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:22:33.290+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_table3', 'scheduled__2024-05-12T00:00:00+00:00', '--job-id', '464', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmp498gz4di']
[2024-05-16T11:22:33.297+0000] {standard_task_runner.py:63} INFO - Started process 588 to run task
[2024-05-16T11:22:33.298+0000] {standard_task_runner.py:91} INFO - Job 464: Subtask import_table3
[2024-05-16T11:22:33.345+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_table3 scheduled__2024-05-12T00:00:00+00:00 [running]> on host 7084a6d88d3b
[2024-05-16T11:22:33.415+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_table3' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-12T00:00:00+00:00'
[2024-05-16T11:22:33.417+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:22:33.426+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:22:33.427+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category_map.sql\n                ']
[2024-05-16T11:22:33.433+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:22:33.500+0000] {subprocess.py:93} INFO - ERROR 1050 (42S01) at line 25: Table 'product_category_map' already exists
[2024-05-16T11:22:33.501+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-16T11:22:33.502+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:22:33.510+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-16T11:22:33.515+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_tables, task_id=import_table3, execution_date=20240512T000000, start_date=20240516T112233, end_date=20240516T112233
[2024-05-16T11:22:33.532+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 464 for task import_table3 (Bash command failed. The command returned a non-zero exit code 1.; 588)
[2024-05-16T11:22:33.565+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-16T11:22:33.577+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:22:33.582+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
